---
title: "Reproducible Document"
author: "Mikkel"
format: html
editor: visual
---

```{r setup}
#| message: false
#| warning: false
library(tidyverse)

post_meal_data <- 
  read_csv2(here::here("data/post-meal-insulin.csv"))
```
## Writing R code

2 + 2

```{r}
2 + 2
```
## About me

- Mikkel Steentoft
- Aarhus University

**I live in Aarhus** *and i like to play padel*

## Simple code

```{r}
3 * 3
```

## Testing for Git

The weather is nice and warm today

## Showing the data

```{r}
post_meal_data

glimpse(post_meal_data)
```

## Plot one continuous variable

```{r}
#| fig-cap: "Distribution of BMI"
#| label: "fig-bmi-histo"
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

See @fig-bmi-histo

## Exercise: discrete plots

```{r}
#| fig-cap: "Glykemi barplot"
#| label: "fig-group-bar"
ggplot(post_meal_data, aes(x = glykemi)) +
  (geom_bar())
```

See @fig-group-bar above for a cool plot!

## Plotting two discrete variables

```{r}
ggplot(post_meal_data, aes(x = Group, fill = 
as.character(glykemi))) +
  geom_bar(position = position_dodge())
```

## Side by side plots

```{r fig-bmi-glycemia}
#| fig-cap: "BMI and glycemia, side by side"
#| fig-subcap: 
#|  - "Distribution of BMI."
#|  - "Number of those with glycemia"
#| layout-ncol: 2
ggplot(post_meal_data, aes(x= BMI)) + 
  geom_histogram()
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```


